config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.role == 'site_admin' } do
    mount Sidekiq::Web => '/sidekiq'
  end

  namespace :api, path: '/', constraints: { subdomain: 'api' } do
    resources :posts, only: [:index, :create]
    get 'search', to: 'posts#search'
  end

  post 'upvote/:post_slug', to: 'votes#upvote', as: 'upvote'
  post 'downvote/:post_slug', to: 'votes#downvote', as: 'downvote'
  get 'query', to: 'search#query', as: 'search_query'
  mount Ckeditor::Engine => '/ckeditor'
  resources :posts
  get 'post_links/:id', to: 'posts#post_links', as: 'post_links'
  get :post_links, controller: :posts
  get 'topic_follow_toggle/:id', to: 'topics#topic_follow_toggle', as: 'topic_follow_toggle'
  resources :topics, only: [:index, :show]
  get 'topic-autocomplete', to: 'topics#autocomplete'
  devise_for :users
  get 'social-connections/disconnect_facebook', to: 'users/social_disconnects#disconnect_facebook', as: :disconnect_facebook
  get 'social-connections/disconnect_twitter', to: 'users/social_disconnects#disconnect_twitter', as: :disconnect_twitter
  get 'smarties', to: 'users#index', as: 'smarties'
  get 'username_validator/:username', to: 'users#username_validator'
  get 'popular', to: 'static#popular', as: 'popular'
  get 'corporate/privacy-policy', to: 'static#privacy_policy', as: 'privacy_policy'
  get 'corporate/terms-conditions', to: 'static#terms_conditions', as: 'terms_conditions'
  get 'corporate/branding', to: 'static#branding', as: 'branding'
  get 'follow/:following_id', to: 'users#follow_toggle', as: 'follow_toggle'
  get ':id', to: 'static#profile', as: 'profile'

  root to: 'static#homepage'

  if Rails.env.production?
    get '404', to: 'errors#not_found'
    get '422', to: 'errors#internal_server_error'
    get '500', to: 'errors#internal_server_error'
  end
end

app/models/post.rb
class Post < ApplicationRecord
  acts_as_paranoid
  is_impressionable counter_cache: true
  mount_uploader :img, ImageUploader
  belongs_to :user, counter_cache: true
  has_many :themes, inverse_of: :post, autosave: true
  has_many :topics, through: :themes, autosave: true
  has_many :post_links, inverse_of: :post, dependent: :destroy
  has_many :votes, dependent: :destroy
  has_many :post_social_shares, inverse_of: :post
  has_one :vote_count, dependent: :destroy

  include PgSearch::Model
  pg_search_scope :search_by_term,
    against: [:title, :content],
    using: {
      tsearch: {
        any_word: true,
        prefix: true
      }
    }

  enum post_status: {
    draft: 0,
    published: 1,
    private_post: 2
  }

  accepts_nested_attributes_for :post_social_shares,
                                allow_destroy: true,
                                reject_if: proc { |attrs| attrs[:provider].blank? }
  accepts_nested_attributes_for :topics
  accepts_nested_attributes_for :themes, allow_destroy: true
  accepts_nested_attributes_for :post_links,
                                allow_destroy: true,
                                reject_if: lambda { |attrs| attrs['link_url'].blank? }

  extend FriendlyId
  friendly_id :title, use: :slugged

  validates_presence_of :title, :user_id

  after_create :generate_vote_count

  def self.with_images
    where.not(img: nil).order('updated_at DESC')
  end

  def topic_titles=(titles)
    transaction do
      themes.delete_all
      titles.each do |title|
        unless title.blank?
          topic = Topic.find_or_create_by!(title: title)
          self.themes.build(topic: topic)
        end
      end
    end
  end

  def topic_titles
    topics.map(&:title)
  end

  def url_for_post
    "http://www.dailysmarty.com/posts/#{self.slug}"
  end

  def associated_topics
    if self.topics.any?
      self.topics.pluck(:title)
    else
      []
    end
  end

  private def generate_vote_count
    VoteCount.create(post_id: self.id, number_of_votes: 0)
  end
end

app/controllers/api/posts_controller.rb
class Api::PostsController < ApplicationController
  protect_from_forgery except: [:create]
  before_action :authenticate, only: [:create]

  def index
    @posts = Post.published.order('created_at DESC').limit(10)
    render json: @posts, adapter: :json
  end

  def search
    if params[:q].blank?
      render json: { errors: 'You need to supply a valid query', status: :unprocessable_entity }
    else
      @posts = Post.search_by_term(params[:q]).page(params[:page]).per(10)
      render json: @posts, adapter: :json
    end
  end

  def create
    @post = Post.new(post_params)
    username = ActionController::HttpAuthentication::Basic::user_name_and_password(request).first
    user = User.find_by_username(username)
    @post.user = user

    if @post.save
      render json: @post, adapter: :json, location: @post
    else
      render json: { errors: @post.errors, status: :unprocessable_entity }
    end
  end

  private

    def post_params
      params.permit(
        :title,
        :content,
        post_links_attributes: [:id, :link_url]
      )
    end

    def authenticate
      authenticate_or_request_with_http_basic do |username, api_key|
        user   = User.find_by_username(username)
        client = ApiClient.find_by_api_key(api_key)
        if (user) && (client) && (user.api_client == client)
          true
        end
      end
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  include ActionView::Helpers::TextHelper
  before_action :set_post, only: [:post_links, :show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :edit, :create, :update, :destroy]
  impressionist actions: [:show]

  def index
    @posts = Post.published.order('created_at desc').page(params[:page]).per(42)
  end

  def show
    authorize @post
    @page_title = @post.title

    unless @post.content.blank?
      @page_description = truncate(ActionView::Base.full_sanitizer.sanitize(@post.content), length: 300)
    end

    @og_logo = @post.img unless @post.img.blank?
    @og_type = 'article'
    impressionist @post
  end

  def post_links
    @post_links = @post.post_links
    render partial: 'post_links'
  end

  def new
    @post = Post.new
    fb_social = @post.post_social_shares.build(provider: 'facebook')
    twitter_social = @post.post_social_shares.build(provider: 'twitter')

    if fb_social || twitter_social
      @social_share_options = [fb_social, twitter_social]
    else
      @social_share_options = []
    end
  end

  def edit
    authorize @post
    @social_share_options = @post.post_social_shares
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    authorize @post
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    authorize @post
    @post.destroy
    respond_to do |format|
      format.html { redirect_to profile_path(current_user.slug), notice: 'Post was successfully deleted.' }
    end
  end

  private
    def set_post
      @post = Post.friendly.find(params[:id])
    end

    def post_params
      params.require(:post).permit(
        :title,
        :content,
        :user_id,
        :img,
        :post_status,
        post_social_shares_attributes: [:id, :provider, :status],
        topic_titles: [],
        post_links_attributes: [:id, :post_id, :_destroy, :link_url]
      )
    end
end

app/helpers/posts_helper.rb
module PostsHelper
  def sanitize_with_whitelist(html)
    return '' unless html

    transformer = lambda do |env|
      if env[:node].element? &&
        env[:node_name] == 'script' &&
        (node_src(env).start_with?("https://gist.github.com/") || node_src(env).start_with?("https://static.codepen.io/assets/embed/ei.js")) &&
        env[:node].text == '' &&
        env[:node].children.empty?
        {node_whitelist: [env[:node]]}
      end
    end

    cleaned_html = Sanitize.fragment(
      html,
      :elements => [
        'header',
        'span',
        'strong',
        'p',
        'h1', 'h2', 'h3', 'h4',
        'img',
        'tt',
        'br',
        'em',
        'u',
        'div'
      ],
      :attributes => {
        'a'    => ['href', 'title', 'class'],
        'span' => ['class'],
        'p'    => ['class'],
        'img'  => ['src', 'class', 'alt', 'style'],
        'div'  => ['class', 'style']
      },
     :transformers => transformer
    )

    cleaned_html
  end

  def node_src(env)
    if env[:node].attributes['src']
      env[:node].attributes['src'].value
    else
      ''
    end
  end


  def auto_link(post_content)
    post_content.gsub(/@\w+/) { |mention| link_to mention, profile_path(mention[1..-1]) }
  end

  def social_icon_renderer(provider)
    if provider == 'facebook'
      'fa-facebook-official'
    elsif provider == 'twitter'
      'fa-twitter-square'
    end
  end

  def post_thumb(post)
    if post.img.post_thumb.blank?
      image_tag('empty-thumb.png')
    else
      image_tag(post.img.post_thumb)
    end
  end

  def post_link_formatter(post_link)
    begin
      link = LinkThumbnailer.generate(post_link)
      post_link_mapper(link)
    rescue LinkThumbnailer::Exceptions, Net::HTTP::Persistent::Error => e
      content = <<~EOL
                  <div class='card post-link-card'>
                    <div class='row'>
                      <div class='col-md-12'>
                        <h2>
                          <a href='#{post_link}' target='_blank'>#{post_link}</a>
                        </h2>
                      </div>
                    </div>
                  </div>
                EOL
      content_tag(:div, content.html_safe, class: 'post-link-wrapper')
    end
  end

  def post_link_mapper(link)
    if !link.videos.empty?
      format_video_link(link)
    elsif !link.images.empty?
      format_image_link(link)
    else
      format_title_link(link)
    end
  end

  def format_title_link(link)
    content = <<~EOL
                <div class='card post-link-card'>
                  <div class='row'>
                    <div class='col-md-12'>
                      <h2>
                        <a href='#{link.url}' target='_blank'>#{link.title}</a>
                      </h2>
                      <p>#{link.description}</p>
                    </div>
                  </div>
                </div>
              EOL
    content_tag(:div, content.html_safe, class: 'post-link-wrapper')
  end

  def format_video_link(link)
    content = <<~EOL
                <div class='card post-link-card'>
                  <div class='row'>
                    <div class='col-md-4'>
                      <div>#{link.videos.first.embed_code}</div>
                    </div>
                    <div class='col-md-8'>
                      <h2>
                        <a href='#{link.url}' target='_blank'>#{link.title}</a>
                      </h2>
                      <p>#{link.description}</p>
                    </div>
                  </div>
                </div>
              EOL
    content_tag(:div, content.html_safe, class: 'post-link-wrapper')
  end

  def format_image_link(link)
    content = <<~EOL
                <div class='card post-link-card'>
                  <div class='row'>
                    <div class='col-md-4'>
                      <img src='#{link.images.first.src.to_s}'>
                    </div>
                    <div class='col-md-8'>
                      <h2>
                        <a href='#{link.url}' target='_blank'>#{link.title}</a>
                      </h2>
                      <p>#{link.description}</p>
                    </div>
                  </div>
                </div>
              EOL
    content_tag(:div, content.html_safe, class: 'post-link-wrapper')
  end
end

app/views/posts/_breadcrumbs.html.slim
.row
  .col-md-12
    ul#breadcrumb
      li
        = link_to '<i class="fa fa-home" aria-hidden="true"></i>'.html_safe, root_path
      li
        = link_to "<i class='fa fa-fire' aria-hidden='true'></i> #{@post.impressions_count}".html_safe, '#'
      - if current_user && policy(@post).update?
        li
          = link_to '<i class="fa fa-pencil" aria-hidden="true"></i>'.html_safe, edit_post_path(@post)
        li
          = link_to '<i class="fa fa-trash" aria-hidden="true"></i>'.html_safe, post_path(@post), method: :delete
      li
        = link_to "<i class='fa fa-user' aria-hidden='true'></i> #{@post.user.slug}".html_safe, profile_path(@post.user.slug)

    - if @post.topics.any?
      - @post.topics.each do |topic|
        span
          = link_to topic.title, topic_path(topic)

app/views/posts/_form.html.slim
.row
  .col-md-12.post-form-wrapper
    = form_for @post, class: 'form-horizontal' do |f|
      - if @post.errors.any?
        #error_explanation
          h2 = "#{pluralize(@post.errors.count, "error")} prohibited this post from being saved:"
          ul
            - @post.errors.full_messages.each do |message|
              li = message

      .row
        .col-md-6
          .form-group
            = f.label :title, class: 'form-label'
            = f.text_field :title, class: 'form-control styled-text-field', autofocus: true
        .col-md-6
          .form-group
            = f.label 'Image upload (optional)'
            br
            = f.file_field :img

        .col-md-6
          .form-group
            = f.select :post_status, [['Draft', 'draft'], ['Published Publicly', 'published'], ['Private Post', 'private_post']], class: 'form-control'

        .col-md-6
          .form-group
            = collection_select(:post, :topic_titles, Topic.all, :title, :title, {include_blank: false}, { :multiple => true, :name => 'post[topic_titles][]', class: 'form-control' })

        .col-md-12
          .form-group
            = cktext_area :post, :content, cols: 40

        .col-md-12
          .form-group.add-link-wrapper
            = f.fields_for :post_links do |post_link_form|
              = render 'post_link_fields', :f => post_link_form
            = link_to_add_association '<i class="fa fa-plus-circle" aria-hidden="true"></i> Add a Link'.html_safe, f, :post_links

        .col-md-12
          .actions
            = f.submit 'Submit', class: 'btn btn-primary'

app/views/posts/_post.html.slim
.post-item-wrapper
  .image-item
    = post_thumb(post)
  .post-link-title
    h2
      = link_to post.title, post_path(post), data: { turbolinks: false }
    - if post.topics.any?
      .topics
        - post.topics.each do |topic|
          = link_to topic.title.upcase, topic_path(topic)
    .post-metadata.user-thumb
      - if UserImage.where(user: post.user).any?
        = "submitted #{distance_of_time_in_words(post.created_at, Time.now) } ago by #{link_to image_tag(UserImage.where(user: post.user).last.img.url) + " " + post.user.username, profile_path(post.user.slug)}".html_safe
      - else
        = "submitted #{distance_of_time_in_words(post.created_at, Time.now) } ago by #{link_to post.user.username, profile_path(post.user.slug)}".html_safe
  .post-votes
    = render partial: 'posts/vote_links', locals: { post: post }

app/views/posts/_post_link_fields.html.slim
.nested-fields.project-tag-fields
  .row
    .col-md-12
      - if f.object.link_url && f.object.valid?
        .col-md-6.theme-card-wrapper
          .theme-content-items
            .t2
              = f.object.link_url
          = link_to_remove_association f, class: 'theme-remove-link btn btn-xs wt-color btn-active-font btn-guide' do
            <i class="fa fa-times" aria-hidden="true"></i>
      - else
        .row
          .col-md-10
            = f.label :link_url, class: 'form-label'
            = f.text_field :link_url, class: 'form-control'
            = link_to_remove_association f do
              <i class="fa fa-times-circle remove-link" aria-hidden="true"></i>

app/views/posts/_post_links.html.slim
- if @post_links.any?
  - @post_links.each do |post_link|
    = post_link_formatter(post_link.link_url)

app/views/posts/_topic_fields.html.slim
.nested-fields.form-inline style='display:inline;'
  = f.text_field :title, :placeholder => 'Create a topic', :label => false

app/views/posts/_vote_links.html.slim
.row.vote-link-wrapper
  - if !current_user
    .score-wrapper
      .col-md-12
        = "Score"
      .col-md-12
        = post.vote_count.number_of_votes
  - else
    .col-md-12
      = link_to "<i class='fa fa-caret-up upvote-link #{arrow_color(post, 'up')}' aria-hidden='true'></i>".html_safe, upvote_path(post_slug: post.slug)
    .col-md-12
      .center-text
        .vote-counter
          = post.vote_count.number_of_votes
    .col-md-12
      = link_to "<i class='fa fa-caret-down downvote-link #{arrow_color(post, 'down')}' aria-hidden='true'></i>".html_safe, downvote_path(post_slug: post.slug)

app/views/posts/edit.html.slim
.full-width-div
  .post-form-wrapper
    .card
      h1 Editing post

      == render 'form'

app/views/posts/index.html.slim
.row
  .col-md-12.page-heading-wrapper
    h1
      = 'Posts'

.full-width-div
  .card
    .col-md-12
      .spacer80
        = render partial: 'shared/google_leaderboard'

      = render @posts

      = paginate @posts

app/views/posts/new.html.slim
.full-width-div
  .post-form-wrapper
    .card
      h1 New post

      == render 'form'

app/views/posts/show.html.slim
css:
  body { background-color: #ffffff !important; }

.full-width-div
  .post-show-wrapper
    .row
      .col-md-12
        .row.post-details-wrapper
          .col-md-11
            h1
              = @post.title
            .post-metadata
              = "#{@post.impressions_count} views"
              - if @post.topics.any?
                - @post.topics.each do |topic|
                  span.post-show-topic-item
                    = link_to topic.title.upcase, topic_path(topic)
            .post-metadata
              = "submitted #{distance_of_time_in_words(@post.created_at, Time.now) } ago by #{link_to @post.user.username, profile_path(@post.user)}".html_safe
              - if current_user && policy(@post).update?
                = link_to ' <i class="fa fa-pencil" aria-hidden="true"></i>'.html_safe, edit_post_path(@post)
                = link_to " <i class='fa fa-trash-o' aria-hidden='true'></i>".html_safe, @post, method: :delete
          .col-md-1
            = render partial: 'posts/vote_links', locals: { post: @post }

    - if !@post.img.blank?
      = image_tag(@post.img.feature_thumb, style: 'margin-bottom: 30px; max-width: 100%; border-radius: 5px;')

    .row
      .col-md-12.post-content
        = auto_link(sanitize_with_whitelist(@post.content)).html_safe
      .col-md-12.post-content
        = render_async post_links_path